import { Inter } from "next/font/google";
import "./globals.css";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Hazeek | Portfolio",
	description: "Hazeeks Portfolio generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en" className="scroll-smooth">
			<body className={inter.className}>
				{children}
				<Script src="../path/to/flowbite/dist/flowbite.min.js"></Script>
			</body>
		</html>
	);
}
